name: labeler
on: [pull_request_target]
jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: 134130/pr-size-labeler@cooper/token-optional
      - name: my test
        run: echo 'hi'
